monitor=,preferred,auto,1.33

env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto

exec-once = waybar &
exec-once = hypridle &
exec-once = swaybg -i $HOME/wallpapers/main.jpg -m fill &
exec-once = $HOME/.local/bin/waybar-autohide &
exec-once = dunst &
exec-once = blueman-applet &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

input {
    kb_layout = us
    kb_variant = colemak_dh
    follow_mouse = 1
    kb_options = caps:super
    touchpad {
        natural_scroll = true
    }
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(ccccccdd)
    col.inactive_border = rgba(1a1a1aaa)
    layout = dwindle
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 3
        passes = 1
        new_optimizations = on
        xray = false
    }
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(0a0a0aee)
    }
}

animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

$mainMod = SUPER

bind = $mainMod, T, exec, kitty
bind = $mainMod, F, exec, librewolf
bind = $mainMod, W, exec, pkill swaybg; swaybg -i $HOME/wallpapers/main.jpg -m fill &
bind = $mainMod, Q, killactive,
bind = $mainMod SHIFT, Q, exit,
bind = $mainMod, M, exit,
bind = $mainMod, D, exec, dolphin
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, wofi --show drun
bind = $mainMod, P, pseudo,
bind = $mainMod, J, layoutmsg, togglesplit
bind = $mainMod, N, movefocus, l
bind = $mainMod, E, movefocus, r
bind = $mainMod, I, movefocus, u
bind = $mainMod, O, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bind = $mainMod, UP, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = $mainMod, DOWN, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = $mainMod, LEFT, exec, brightnessctl set 5%-
bind = $mainMod, RIGHT, exec, brightnessctl set +5%
