format = "$all"

[character]
success_symbol = "[➜](bold #cccccc)"
error_symbol = "[➜](bold #888888)"

[directory]
style = "#aaaaaa"

[git_branch]
style = "#cccccc"

[git_status]
style = "#888888"

[username]
style_user = "#cccccc"
style_root = "#888888"

[hostname]
style = "#777777"
