format = "$all"

[character]
success_symbol = "[➜](bold #ffffff)"
error_symbol = "[➜](bold #ff8800)"

[directory]
style = "#aaaaaa"

[git_branch]
style = "#ffffff"

[git_status]
style = "#888888"

[username]
style_user = "#eeeeee"
style_root = "#ff8800"

[hostname]
style = "#777777"
